"""Following is the handoff from Planner to Writer, specifying agent, input type, and callback"""
from agents import handoff, RunContextWrapper
from agents.extensions.handoff_prompt import RECOMMENDED_PROMPT_PREFIX
from pydantic import BaseModel

from my_agents.planner import planner_agent
from my_agents.writer import writer_agent
from schemas.search_plan import SearchPlan


class PlannerToWriterInput(BaseModel):
    original_query: str  # The original user query string
    search_plan: SearchPlan  # The search plan generated by the Planner

def on_planner_to_writer(ctx: RunContextWrapper[None], input_data: PlannerToWriterInput):
    print("➡️ Transfer: Planner → Writer")  # Print a message indicating the handoff took place

handoff_to_writer = handoff(
    agent = writer_agent,  # must point to the writer that has the verifier handoff
    input_type = PlannerToWriterInput,
    on_handoff = on_planner_to_writer,
    tool_name_override = "transfer_to_writer",
    tool_description_override = "Transfer to Writer with original query and search plan")

"""Following is the clone of the Planner agent and add handoff instructions and the handoff tool to Writer. 
We are enhancing the prompt to include openai recommended prompt prefix and the handoff tool to the planner agent."""
planner_with_handoff = planner_agent.clone(
    instructions=f"""{RECOMMENDED_PROMPT_PREFIX}\n\n"""
                 + planner_agent.instructions
                 + "\n\nWhen you have produced the SearchPlan, call the handoff tool `handoff_to_writer` with this JSON input: {{ original_query: <the user query>, search_plan: <the SearchPlan JSON> }}.\n",
    handoffs=[handoff_to_writer],  # Add the handoff to Writer
)
